name: Java CI with Maven

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Generate Jacoco Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: target/test-results/jacoco/jacoco.csv
        generate-branches-badge: true

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/test-results/jacoco/

    - name: Print tests coverage in PR comments
      uses: mshick/add-pr-comment@v2
      with:
        message: |
          ${{ steps.jacoco.outputs.coverage }}